### ISSUE TITLE
About Flasks Usage

### ISSUE THREAD

**Issue by TsumiHokiro** [TheHorscht/Anvil-of-Destiny#2]
I just checked the ToDo and I was wondering if you'd accept a suggestion; instead of making it so that flask is like the others, drag and drop into the world, why not the opposite, hold the wand and items close to the anvil and interact with it?
This way you can actually interact with the anvil faster and also you don't run into the problem of having to open the inventory interface and running the risk of an enemy ambushing you out of nowhere.
A minus would be less immersion, as well as somewhat of a reduce in certainty on which item you're really using on the anvil but that's not really something you can't get used to?

An alternative could be making some sort of world inventory, if that is possible. I believe there is that Noita-together inventory mod, from which the anvil could pull the items from? That way you'd retain the drag-drop style, including a safe place to deposit the flask without the risk of breaking the flask when throwing it on the world.
Though, seriously, I think this is a bit of overkill...

**Comment by TheHorscht** [comment]
Not sure if changing things this late won't confuse and irritate people. My TODO lists are mostly just a list of "maybes", any time I have an idea or see a suggestion that I like it gets added, without any guaranteed intention of ever implementing it 😅.

I wish it was possible to create a custom GUI with drag&drop functionality, but it doesn't seem to be quite possible with the current modding API, at least not satisfactorily. There is a small draggable-gui library that I made for my minimap and it works, but the biggest problem is preventing default left click functionality from activating while the left mouse button is down. For instance, if you have a potion selected while dragging the GUI around, you're constantly spraying it. Same with wands, you're firing them while dragging but I found a workaround for that which disables the wand shooting while the mouse is over the GUI element. But I would have to add a workaround for every possible item like this and if it bugs out and doesn't restore the functionality after leaving the GUI element, that would be a huuuge bug. Imagine suddenly not being able to shoot your wand and you don't know why.

Noita-together's inventory doesn't seem to help here, since you also can't drag&drop (at least not into and from the NT-inventory).

The best solution I can think of right now would maybe be to show a GUI with a custom tooltip of the currently selected item while standing on the anvil, which shows the spells and the wand stats so you know what you have selected and what you're adding. Then just add it with [ E ]. This way I could also show what's already in there, and even add a tooltip for what kind of effect to expect? Like "Add [Fire potion], gain 3-4 of the following spells:".
Could be interesting, but also a lot of work and potential for new bugs.

**Comment by TsumiHokiro** [comment]
I know, the idea of making things too complex would add the potential for too many bugs is really annoying. Also, I thought it would be also that, a place for your ideas. I just thought of giving some thought on something that annoys me as well since I saw it on that file (and maybe I could help somehow or another).
The thing about the Flasks and only the Flasks being different in placement is really annoying, specially when you're doing multiple editing of a wand on the same anvil (it's annoying getting a bunch of drag-and-drop items close to an anvil and then placing them on the anvil... but this is me and I bet not many do this).

Also, I agree with you that a GUI would be awesome and all but I think that that would end up showing up a bunch of potential ground for bugs, but I think we could do something like that, the result without having to work with a GUI. I think if you add a place in the Anvil where you put the items in by interacting, sort of like the altar where you find items, and make it float as if in the air, and make it so that the anvil uses that item, maybe it would work?
    What I have in mind is what Wand Workshop does. On their case they require you to drag and drop an item into an area but the item will be displayed in-world and it will be interact-able as well but it can be put off the 'machine' in case of giving up.

**Comment by TheHorscht** [comment]
Altars would probably take up too much space in the already tiny pixel scenes. The only thing I can see myself doing is the tooltip GUI for wands and then inserting them with [ E ] instead of having to throw them. Maybe not right now though, I'm not very motivated right now.

**Comment by TsumiHokiro** [comment]
Well, the idea was not to make altars per see. The anvil already has 3 parts, the west, middle and east one, and the anvil accepts 3 inputs as well. The items would float on these parts. Maybe it would be better for them to float above the 2 lines?
Well, anyway, best regards.

**Comment by TheHorscht** [comment]
You mean make them float above the statues? Maybe in their hands? I dunno that seems like it wouldn't make it clear enough that the items is now "in" the anvil. It would look like more like a reward already. Also if the wands were floating then enemies could snatch them up and walk away with them or kill you with them. And making potions float could break them and would duplicate the bottle, I kinda like that they are being emptied and you're left with the empty bottle so at least it's refillable.
What do you mean by "above the 2 lines", which lines?
